# Generated by Django 5.0.6 on 2024-08-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carrer", "0018_delete_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=255)),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="team_profiles/"
                    ),
                ),
                ("about", models.TextField(blank=True, null=True)),
                (
                    "linkedin_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
            ],
        ),
    ]
